# Generated by Django 3.0.4 on 2020-03-26 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('tree_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('parent', models.ForeignKey(db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='tree.Tree', verbose_name='Родитель')),
            ],
            options={
                'db_table': 'tree',
            },
        ),
    ]
